### ISSUE TITLE
Music/Soundeffects

### ISSUE THREAD

**Issue by sosaidi** [Ne0Strix/open-realms#10]
# User Story
As a player, I want to have background music and sound effects in the game, because it adds to the overall gaming experience.

## Description
Integrate background music and sound effects into the game, such as for different game actions and events.

## Tasks:
- [ ] Collect appropriate background music and sound effects for the game
- [ ] Implement music and sound effect players in the app
- [ ] Integrate music and sound effects into relevant parts of the app
- [ ] Test whether music and sound effects are playing correctly
