### ISSUE TITLE
Game initialization 

### ISSUE THREAD

**Issue by Kranosos** [Ne0Strix/open-realms#109]
# User Story
As a developer I want all the cards and player/player-turn information to be sent to the clients at the start of the game.

## Description
This issue is a sub-issue of #94 and will be worked on, on a separate branch coming from the main server branch. It shall enable the server and clients to communicate the initial game state at the beginning of a session. 

## Tasks:
- [x] send cards to clients
- [x] send information about which player goes first
- [x] send initial player-stats and names
