### ISSUE TITLE
Pooling values from user-played cards

### ISSUE THREAD

**Issue by Benjamin-Dippold** [Ne0Strix/open-realms#11]
# User Story
As a player, I want to see a combined amount of attack, healing and money of the played cards for this turn.

## Description
Pool all attack-, health- and money-values from played cards each round, for use in attacking, healing and market buying. 

## Tasks:
- [x] #31
- [x] #32
- [x] #33

**Comment by Ne0Strix** [comment]
# User Story
As a player, I want to see a combined amount of attack, healing and money of the played cards for this turn.

## Description
Pool all attack-, health- and money-values from played cards each round, for use in attacking, healing and market buying. 

## Tasks:
- [ ] cards can add their value to the pool
- [ ] display current total
- [ ] reset totals at end of turn
