### ISSUE TITLE
Synergies

### ISSUE THREAD

**Issue by Ne0Strix** [Ne0Strix/open-realms#118]
# User Story
As a player, I want Cards to have additional abilites, if a card of the same type has already been played.

## Description
All cards have a certain type (Guild, Imperial, Necros, Wild) and some cards have additional abilites that only tigger when another card of the same type has been played in this turn. The Type and the new abilites should be represented in the View.

## Tasks:
- [x] add Card Type to Card-Model
- [x] add Synergy-abilites to Card-Model
- [x] add Card Type and Synergy-abilites to CardView
- [x] handle Synergy-abilites in Server backend
