### ISSUE TITLE
Champions

### ISSUE THREAD

**Issue by Ne0Strix** [Ne0Strix/open-realms#119]
# User Story
As a Player, I want champions to protect me from damage and have the ability to use effects once per turn.

## Description
A champion is a special type of card that has its own HP-counter, in addition to the usual effects.
When a champion is played to the play-area it stays there until its HP are zero. Any effects and synergies can be used once per turn. Two types of Champions can be differentiated: guards and *non*-guards. The former *has* to be attacked before dealing damage to the player whereas the latter one can be attacked optionally (the attacking player decides the target). 

## Tasks:
- [x] Make the necessary changes to the backend to implement champions and guards 
- [x] create UI elements for displaying and attacking them
- [x] handle the resulting new network communication

**Comment by Benjamin-Dippold** [comment]
Closed by #131
