### ISSUE TITLE
Show Player Hand

### ISSUE THREAD

**Issue by Ne0Strix** [Ne0Strix/open-realms#13]
# User Story
As a player, I want to see my hand of cards.

## Description
A "hand" class stores a collection of cards, that is displayed in a separate UI component for the HandView.

## Tasks:
- [ ] create necessary model classes (e.g. `Card`, `Player`, `Hand`)
- [ ] design and implement a UI-component (e.g. custom `HandView` view or layout)
- [ ] integrate the `HandView` to the game activity or fragment
