### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by sosaidi** [Ne0Strix/open-realms#8]
# User Story
As a player, I want to be able to access the game menu easily, because I want to customize my game settings.

## Description
Develop a menu that allows players to customize game settings, such as sound and graphics.

## Tasks:
- [ ] Design a user interface for the game menu
- [ ] Implement the game menu and its functions
- [ ] Link the menu to other functions of the app
- [ ] Test whether the menu works smoothly
