### ISSUE TITLE
Integrate hero statistics into UI

### ISSUE THREAD

**Issue by Benjamin-Dippold** [Ne0Strix/open-realms#92]
# User Story
As a Player I want to see each player's statistics.

## Description
 The UI should reflect each player's statistics matching the style of the game. The implementation should allow for adaption.

## Tasks:
TODO:

- [x]  find and implement suitable Layout and Background for the Element
- [x]  find and implement suitable icon for the health
- [x] add the Text to the Element
- [x] Text must be updated when relevant game actions occur
